---
- name: Deploy fail2ban to protect SSH from brute force
  hosts: all
  vars:
    email_address: "john@doe.com"
  tasks:
    - name: Install fail2ban package and needed dependencies
      apt: pkg={{ item }} state='latest' update_cache='yes'
      become: True
      with_items:
        - fail2ban

    - name: put fail2ban config file in place
      template: >
        src=jail.local.j2
        dest=/etc/fail2ban/jail.local
        backup=yes
        mode=0644
      register: fail2ban_conf
      become: True

    - name: start fail2ban service if not yet running
      service: >
        name=fail2ban
        state=started
        enabled=yes
      become: True

    - name: restart fail2ban service if config was changed
      service: >
        name=fail2ban
        state=reloaded
      when: fail2ban_conf.changed == True
      become: True
