---
- name: Deploy a TOR relay
  hosts: torserver
  vars:
    nick_name: "TorRelayNickname"
    full_name: "John Doe"
    email_address: "john@doe.com"
    tor_user: "debian-tor"
    tor_orport: 9001
    tor_relay_bandwidth_rate: "2500 KB"
    tor_relay_bandwidth_burst: "3000 KB"
    tor_accounting_max: "500 GB"
    tor_accounting_start: "month 1 00:00"
    tor_dir_port: 9030
  tasks:
    - name: Install gnupg package
      apt: name='gnupg' state='latest' update_cache='yes'
      become: True

    - name: Add apt key
      apt_key: keyserver=keys.gnupg.net id=886DDD89 state=present
      become: True

    - name: Setup TOR apt repo
      apt_repository: >
        repo='deb http://deb.torproject.org/torproject.org {{ ansible_lsb.codename }} main'
        state=present
        update_cache=yes
      become: True

    - name: Install TOR package
      apt: name='tor' state='latest' update_cache='yes'
      become: True

    - name: put Tor config file in place
      template: >
        src=torrc.j2
        dest=/etc/tor/torrc
        backup=yes
        owner={{ tor_user }}
        mode=0644
      register: tor_conf
      become: True

    - name: create/ensure correct directory permissions
      file: >
        path={{ item }}
        recurse=yes
        state=directory
        owner={{ tor_user }}
        group={{ tor_user }}
        mode=0750
      with_items:
        -  /var/log/tor
        -  /var/lib/tor
      become: True

    - name: start Tor service if not yet running
      service: >
        name=tor
        state=started
        enabled=yes
      become: True

    - name: restart Tor service if Tor config was changed
      service: >
        name=tor
        state=reloaded
      when: tor_conf.changed == True
      become: True
